export interface Industry {
  slug: string
  name: string
  category: "Trades" | "Home Services" | "Property" | "Automotive" | "Health" | "Beauty" | "Hospitality"
  metaTitle: string
  metaDescription: string
  h1: string
  intro: string
  challenges: string
  relatedIndustries: string[]
  relatedLocations: string[]
}

export const industries: Industry[] = [
  // ─── Trades ────────────────────────────────────────────────────────
  {
    slug: "builders",
    name: "Builders",
    category: "Trades",
    metaTitle: "Builders Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds builders websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Builders Websites Built to Compete Locally",
    intro: "Most customers decide who to contact in under a minute. If you’re a builders business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in builders websites: trust signals for high-value jobs; reviews that reinforce reliability; project categories and photo proof; clear service areas. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["construction-companies", "scaffolders", "roofers", "plumbers", "electricians"],
    relatedLocations: ["brighton", "sussex", "london", "manchester", "birmingham"],
  },
  {
    slug: "construction-companies",
    name: "Construction Companies",
    category: "Trades",
    metaTitle: "Construction Companies Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for construction companies. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Construction Companies",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a construction companies business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in construction companies websites: fast mobile experience; simple, obvious calls-to-action; service-area clarity; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["builders", "scaffolders", "roofers", "driveway-companies", "plumbers"],
    relatedLocations: ["london", "manchester", "birmingham", "leeds", "sussex"],
  },
  {
    slug: "scaffolders",
    name: "Scaffolders",
    category: "Trades",
    metaTitle: "Scaffolders Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for scaffolders. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Web Design, SEO Foundation & Review Growth for Scaffolders",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a scaffolders business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in scaffolders websites: proof (projects / accreditations); commercial-friendly service breakdown; areas covered for contracts; safety/compliance positioning. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["builders", "construction-companies", "roofers", "painters-and-decorators"],
    relatedLocations: ["sussex", "london", "manchester", "brighton", "crawley"],
  },
  {
    slug: "flooring-shops",
    name: "Flooring Shops",
    category: "Trades",
    metaTitle: "Flooring Shops Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for flooring shops. Built for enquiries, trust and local visibility.",
    h1: "Flooring Shops Websites Built to Compete Locally",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a flooring shops business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in flooring shops websites: fast mobile experience; clear service breakdown; simple, obvious calls-to-action; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["carpet-cleaners", "builders", "painters-and-decorators", "estate-agents"],
    relatedLocations: ["brighton", "worthing", "london", "manchester", "horsham"],
  },
  // ─── Home Services ────────────────────────────────────────────────────────
  {
    slug: "carpet-cleaners",
    name: "Carpet Cleaners",
    category: "Home Services",
    metaTitle: "Carpet Cleaners Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for carpet cleaners. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Carpet Cleaners Websites Built to Compete Locally",
    intro: "Most customers decide who to contact in under a minute. If you’re a carpet cleaners business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in carpet cleaners websites: fast mobile experience; service-area clarity; simple, obvious calls-to-action; clear service breakdown. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["cleaning-companies", "flooring-shops", "landscapers", "painters-and-decorators"],
    relatedLocations: ["sussex", "brighton", "london", "worthing", "crawley"],
  },
  // ─── Trades ────────────────────────────────────────────────────────
  {
    slug: "driveway-companies",
    name: "Driveway Companies",
    category: "Trades",
    metaTitle: "Driveway Companies Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for driveway companies. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Web Design, SEO Foundation & Review Growth for Driveway Companies",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a driveway companies business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in driveway companies websites: strong proof and trust signals; fast mobile experience; service-area clarity; clear service breakdown. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["builders", "construction-companies", "landscapers", "painters-and-decorators"],
    relatedLocations: ["sussex", "brighton", "london", "horsham", "worthing"],
  },
  {
    slug: "roofers",
    name: "Roofers",
    category: "Trades",
    metaTitle: "Roofers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for roofers. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Roofers",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a roofers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in roofers websites: clear service areas and travel radius; fast mobile call-to-action for urgent work; proof above the fold (jobs + reviews); a quote flow that isn’t a dead-end form. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["builders", "scaffolders", "construction-companies", "plumbers", "electricians"],
    relatedLocations: ["sussex", "brighton", "london", "crawley", "eastbourne"],
  },
  {
    slug: "plumbers",
    name: "Plumbers",
    category: "Trades",
    metaTitle: "Plumbers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for plumbers. Built for enquiries, trust and local visibility.",
    h1: "Get More Enquiries with a Stronger Plumbers Website",
    intro: "Most customers decide who to contact in under a minute. If you’re a plumbers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in plumbers websites: service-area coverage stated plainly; emergency CTA and availability; clear service breakdown (leaks, boilers, installs); fast-loading pages on mobile. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["electricians", "builders", "roofers", "locksmiths"],
    relatedLocations: ["brighton", "sussex", "london", "worthing", "crawley"],
  },
  {
    slug: "electricians",
    name: "Electricians",
    category: "Trades",
    metaTitle: "Electricians Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for electricians. Built for enquiries, trust and local visibility.",
    h1: "Get More Enquiries with a Stronger Electricians Website",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a electricians business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in electricians websites: certifications and compliance trust signals; fast mobile experience for urgent faults; clear service list (domestic, commercial, EV, callouts); service-area clarity (where you actually cover). These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["plumbers", "builders", "roofers", "locksmiths"],
    relatedLocations: ["brighton", "sussex", "london", "crawley", "horsham"],
  },
  {
    slug: "painters-and-decorators",
    name: "Painters and Decorators",
    category: "Trades",
    metaTitle: "Painters and Decorators Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for painters and decorators. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Painters and Decorators",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a painters and decorators business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in painters and decorators websites: clear service breakdown; fast mobile experience; service-area clarity; simple, obvious calls-to-action. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["builders", "flooring-shops", "driveway-companies", "landscapers", "cleaning-companies"],
    relatedLocations: ["sussex", "brighton", "london", "chichester", "eastbourne"],
  },
  // ─── Property ────────────────────────────────────────────────────────
  {
    slug: "estate-agents",
    name: "Estate Agents",
    category: "Property",
    metaTitle: "Estate Agents Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds estate agents websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Estate Agents Websites Built to Compete Locally",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a estate agents business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in estate agents websites: strong proof and trust signals; clear service breakdown; fast mobile experience; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["letting-agents", "builders", "cleaning-companies", "locksmiths"],
    relatedLocations: ["brighton", "london", "sussex", "horsham", "chichester"],
  },
  {
    slug: "letting-agents",
    name: "Letting Agents",
    category: "Property",
    metaTitle: "Letting Agents Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for letting agents. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Letting Agents Websites Built to Compete Locally",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a letting agents business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in letting agents websites: strong proof and trust signals; service-area clarity; fast mobile experience; simple, obvious calls-to-action. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["estate-agents", "cleaning-companies", "locksmiths", "builders"],
    relatedLocations: ["brighton", "london", "sussex", "hove", "crawley"],
  },
  // ─── Hospitality ────────────────────────────────────────────────────────
  {
    slug: "restaurants",
    name: "Restaurants",
    category: "Hospitality",
    metaTitle: "Restaurants Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds restaurants websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Get More Enquiries with a Stronger Restaurants Website",
    intro: "Most customers decide who to contact in under a minute. If you’re a restaurants business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in restaurants websites: service-area clarity; fast mobile experience; strong proof and trust signals; clear service breakdown. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["cafes", "barbers", "salons", "cleaning-companies"],
    relatedLocations: ["brighton", "london", "sussex", "manchester", "edinburgh"],
  },
  {
    slug: "cafes",
    name: "Cafes",
    category: "Hospitality",
    metaTitle: "Cafes Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds cafes websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Get More Enquiries with a Stronger Cafes Website",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a cafes business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in cafes websites: clear service breakdown; simple, obvious calls-to-action; service-area clarity; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["restaurants", "salons", "barbers", "cleaning-companies"],
    relatedLocations: ["brighton", "hove", "london", "lewes", "edinburgh"],
  },
  // ─── Automotive ────────────────────────────────────────────────────────
  {
    slug: "garages",
    name: "Garages",
    category: "Automotive",
    metaTitle: "Garages Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for garages. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Web Design, SEO Foundation & Review Growth for Garages",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a garages business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in garages websites: clear service breakdown; service-area clarity; simple, obvious calls-to-action; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["mechanics", "builders", "electricians", "cleaning-companies"],
    relatedLocations: ["sussex", "brighton", "crawley", "london", "manchester"],
  },
  {
    slug: "mechanics",
    name: "Mechanics",
    category: "Automotive",
    metaTitle: "Mechanics Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for mechanics. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Mechanics",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a mechanics business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in mechanics websites: service-area clarity; fast mobile experience; clear service breakdown; simple, obvious calls-to-action. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["garages", "builders", "electricians", "plumbers"],
    relatedLocations: ["sussex", "brighton", "crawley", "london", "birmingham"],
  },
  // ─── Home Services ────────────────────────────────────────────────────────
  {
    slug: "cleaning-companies",
    name: "Cleaning Companies",
    category: "Home Services",
    metaTitle: "Cleaning Companies Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for cleaning companies. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Get More Enquiries with a Stronger Cleaning Companies Website",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a cleaning companies business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in cleaning companies websites: simple, obvious calls-to-action; fast mobile experience; clear service breakdown; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["carpet-cleaners", "landscapers", "letting-agents", "estate-agents"],
    relatedLocations: ["sussex", "brighton", "london", "hove", "crawley"],
  },
  {
    slug: "landscapers",
    name: "Landscapers",
    category: "Home Services",
    metaTitle: "Landscapers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for landscapers. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Landscapers",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a landscapers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in landscapers websites: strong proof and trust signals; clear service breakdown; fast mobile experience; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["tree-surgeons", "builders", "driveway-companies", "painters-and-decorators", "cleaning-companies"],
    relatedLocations: ["sussex", "brighton", "horsham", "london", "chichester"],
  },
  {
    slug: "tree-surgeons",
    name: "Tree Surgeons",
    category: "Home Services",
    metaTitle: "Tree Surgeons Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for tree surgeons. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Get More Enquiries with a Stronger Tree Surgeons Website",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a tree surgeons business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in tree surgeons websites: simple, obvious calls-to-action; strong proof and trust signals; clear service breakdown; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["landscapers", "builders", "roofers", "cleaning-companies"],
    relatedLocations: ["sussex", "brighton", "crawley", "uckfield", "crowborough"],
  },
  {
    slug: "locksmiths",
    name: "Locksmiths",
    category: "Home Services",
    metaTitle: "Locksmiths Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for locksmiths. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Get More Enquiries with a Stronger Locksmiths Website",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a locksmiths business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in locksmiths websites: service-area clarity; strong proof and trust signals; clear service breakdown; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["plumbers", "electricians", "estate-agents", "letting-agents"],
    relatedLocations: ["sussex", "brighton", "london", "crawley", "hastings"],
  },
  // ─── Health ────────────────────────────────────────────────────────
  {
    slug: "dentists",
    name: "Dentists",
    category: "Health",
    metaTitle: "Dentists Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds dentists websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Get More Enquiries with a Stronger Dentists Website",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a dentists business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in dentists websites: clear service breakdown; strong proof and trust signals; service-area clarity; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["physios", "gyms", "salons", "barbers"],
    relatedLocations: ["brighton", "sussex", "london", "worthing", "eastbourne"],
  },
  {
    slug: "physios",
    name: "Physios",
    category: "Health",
    metaTitle: "Physios Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds physios websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Web Design, SEO Foundation & Review Growth for Physios",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a physios business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in physios websites: strong proof and trust signals; service-area clarity; simple, obvious calls-to-action; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["dentists", "gyms", "salons"],
    relatedLocations: ["brighton", "sussex", "london", "worthing", "eastbourne"],
  },
  {
    slug: "gyms",
    name: "Gyms",
    category: "Health",
    metaTitle: "Gyms Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for gyms. Built for enquiries, trust and local visibility.",
    h1: "Gyms Websites Built to Compete Locally",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a gyms business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in gyms websites: fast mobile experience; service-area clarity; simple, obvious calls-to-action; clear service breakdown. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["physios", "dentists", "salons", "barbers"],
    relatedLocations: ["brighton", "sussex", "london", "manchester", "leeds"],
  },
  // ─── Beauty ────────────────────────────────────────────────────────
  {
    slug: "salons",
    name: "Salons",
    category: "Beauty",
    metaTitle: "Salons Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for salons. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Salons",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a salons business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in salons websites: fast mobile experience; clear service breakdown; service-area clarity; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["barbers", "dentists", "physios", "gyms"],
    relatedLocations: ["brighton", "sussex", "london", "hove", "eastbourne"],
  },
  {
    slug: "barbers",
    name: "Barbers",
    category: "Beauty",
    metaTitle: "Barbers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for barbers. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Barbers",
    intro: "Most customers decide who to contact in under a minute. If you’re a barbers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in barbers websites: clear service breakdown; fast mobile experience; strong proof and trust signals; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["salons", "gyms", "restaurants", "cafes"],
    relatedLocations: ["brighton", "sussex", "london", "manchester", "hastings"],
  },
  // ─── Trades ────────────────────────────────────────────────────────
  {
    slug: "tilers",
    name: "Tilers",
    category: "Trades",
    metaTitle: "Tilers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds tilers websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Web Design, SEO Foundation & Review Growth for Tilers",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a tilers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in tilers websites: clear service breakdown; service-area clarity; fast mobile experience; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["cleaning-companies", "gyms", "pest-control", "scaffolders", "waste-removal"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "kitchen-fitters",
    name: "Kitchen Fitters",
    category: "Trades",
    metaTitle: "Kitchen Fitters Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for kitchen fitters. Built for enquiries, trust and local visibility.",
    h1: "Get More Enquiries with a Stronger Kitchen Fitters Website",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a kitchen fitters business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in kitchen fitters websites: service-area clarity; simple, obvious calls-to-action; clear service breakdown; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["tyre-shops", "garages", "letting-agents", "cafes", "bathroom-fitters"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "bathroom-fitters",
    name: "Bathroom Fitters",
    category: "Trades",
    metaTitle: "Bathroom Fitters Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for bathroom fitters. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Bathroom Fitters",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a bathroom fitters business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in bathroom fitters websites: clear service breakdown; strong proof and trust signals; service-area clarity; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["dental-implants", "locksmiths", "tyre-shops", "bricklayers", "opticians"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "plasterers",
    name: "Plasterers",
    category: "Trades",
    metaTitle: "Plasterers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds plasterers websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Web Design, SEO Foundation & Review Growth for Plasterers",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a plasterers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in plasterers websites: fast mobile experience; strong proof and trust signals; service-area clarity; simple, obvious calls-to-action. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["tilers", "removal-companies", "locksmiths", "builders", "cctv-installers"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "bricklayers",
    name: "Bricklayers",
    category: "Trades",
    metaTitle: "Bricklayers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for bricklayers. Built for enquiries, trust and local visibility.",
    h1: "Bricklayers Websites Built to Compete Locally",
    intro: "Most customers decide who to contact in under a minute. If you’re a bricklayers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in bricklayers websites: simple, obvious calls-to-action; service-area clarity; strong proof and trust signals; clear service breakdown. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["builders", "glaziers", "plasterers", "physios", "garages"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "groundworks",
    name: "Groundworks Companies",
    category: "Trades",
    metaTitle: "Groundworks Companies Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds groundworks companies websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Web Design, SEO Foundation & Review Growth for Groundworks Companies",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a groundworks companies business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in groundworks companies websites: simple, obvious calls-to-action; service-area clarity; clear service breakdown; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["tilers", "electricians", "car-dealers", "carpet-cleaners", "gyms"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "loft-conversions",
    name: "Loft Conversion Specialists",
    category: "Trades",
    metaTitle: "Loft Conversion Specialists Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for loft conversion specialists. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Web Design, SEO Foundation & Review Growth for Loft Conversion Specialists",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a loft conversion specialists business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in loft conversion specialists websites: simple, obvious calls-to-action; service-area clarity; clear service breakdown; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["roofers", "scaffolders", "electricians", "glaziers", "boiler-engineers"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  // ─── Home Services ────────────────────────────────────────────────────────
  {
    slug: "window-fitters",
    name: "Window Fitters",
    category: "Home Services",
    metaTitle: "Window Fitters Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for window fitters. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Window Fitters Websites Built to Compete Locally",
    intro: "Most customers decide who to contact in under a minute. If you’re a window fitters business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in window fitters websites: strong proof and trust signals; fast mobile experience; service-area clarity; simple, obvious calls-to-action. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["mot-centres", "physios", "groundworks", "bricklayers", "flooring-shops"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "glaziers",
    name: "Glaziers",
    category: "Home Services",
    metaTitle: "Glaziers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for glaziers. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Get More Enquiries with a Stronger Glaziers Website",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a glaziers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in glaziers websites: clear service breakdown; service-area clarity; fast mobile experience; simple, obvious calls-to-action. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["roofers", "estate-agents", "takeaways", "boiler-engineers", "tyre-shops"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "boiler-engineers",
    name: "Boiler Engineers",
    category: "Home Services",
    metaTitle: "Boiler Engineers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for boiler engineers. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Get More Enquiries with a Stronger Boiler Engineers Website",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a boiler engineers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in boiler engineers websites: service-area clarity; strong proof and trust signals; clear service breakdown; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["removal-companies", "letting-agents", "barbers", "kitchen-fitters", "landscapers"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "hvac-engineers",
    name: "HVAC Engineers",
    category: "Home Services",
    metaTitle: "HVAC Engineers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for hvac engineers. Built for enquiries, trust and local visibility.",
    h1: "HVAC Engineers Websites Built to Compete Locally",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a hvac engineers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in hvac engineers websites: fast mobile experience; service-area clarity; strong proof and trust signals; clear service breakdown. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["pubs", "plumbers", "removal-companies", "massage-therapists", "locksmiths"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "pest-control",
    name: "Pest Control",
    category: "Home Services",
    metaTitle: "Pest Control Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for pest control. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Pest Control Websites Built to Compete Locally",
    intro: "Most customers decide who to contact in under a minute. If you’re a pest control business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in pest control websites: fast mobile experience; simple, obvious calls-to-action; clear service breakdown; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["flooring-shops", "massage-therapists", "tilers", "plumbers", "physios"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "window-cleaners",
    name: "Window Cleaners",
    category: "Home Services",
    metaTitle: "Window Cleaners Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for window cleaners. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Get More Enquiries with a Stronger Window Cleaners Website",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a window cleaners business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in window cleaners websites: service-area clarity; strong proof and trust signals; simple, obvious calls-to-action; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["mot-centres", "takeaways", "chiropractors", "electricians", "salons"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "removal-companies",
    name: "Removal Companies",
    category: "Home Services",
    metaTitle: "Removal Companies Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for removal companies. Built for enquiries, trust and local visibility.",
    h1: "Get More Enquiries with a Stronger Removal Companies Website",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a removal companies business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in removal companies websites: service-area clarity; clear service breakdown; simple, obvious calls-to-action; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["window-fitters", "chiropractors", "electricians", "opticians", "bricklayers"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "waste-removal",
    name: "Waste Removal",
    category: "Home Services",
    metaTitle: "Waste Removal Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for waste removal. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Waste Removal Websites Built to Compete Locally",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a waste removal business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in waste removal websites: simple, obvious calls-to-action; fast mobile experience; clear service breakdown; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["cleaning-companies", "tyre-shops", "scaffolders", "nail-salons", "security-installers"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "skip-hire",
    name: "Skip Hire",
    category: "Home Services",
    metaTitle: "Skip Hire Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds skip hire websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Web Design, SEO Foundation & Review Growth for Skip Hire",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a skip hire business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in skip hire websites: clear service breakdown; simple, obvious calls-to-action; fast mobile experience; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["mot-centres", "dental-implants", "physios", "pubs", "landscapers"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "security-installers",
    name: "Security Installers",
    category: "Home Services",
    metaTitle: "Security Installers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for security installers. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Web Design, SEO Foundation & Review Growth for Security Installers",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a security installers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in security installers websites: simple, obvious calls-to-action; service-area clarity; fast mobile experience; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["beauty-clinics", "bathroom-fitters", "dentists", "tree-surgeons", "skip-hire"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "cctv-installers",
    name: "CCTV Installers",
    category: "Home Services",
    metaTitle: "CCTV Installers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for cctv installers. Built for enquiries, trust and local visibility.",
    h1: "CCTV Installers Websites Built to Compete Locally",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a cctv installers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in cctv installers websites: service-area clarity; simple, obvious calls-to-action; strong proof and trust signals; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["loft-conversions", "groundworks", "scaffolders", "security-installers", "tilers"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "solar-installers",
    name: "Solar Installers",
    category: "Home Services",
    metaTitle: "Solar Installers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds solar installers websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Web Design, SEO Foundation & Review Growth for Solar Installers",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a solar installers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in solar installers websites: clear service breakdown; service-area clarity; simple, obvious calls-to-action; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["scaffolders", "electricians", "security-installers", "dental-implants", "opticians"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  // ─── Automotive ────────────────────────────────────────────────────────
  {
    slug: "car-detailers",
    name: "Car Detailers",
    category: "Automotive",
    metaTitle: "Car Detailers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds car detailers websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Get More Enquiries with a Stronger Car Detailers Website",
    intro: "Most customers decide who to contact in under a minute. If you’re a car detailers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in car detailers websites: fast mobile experience; strong proof and trust signals; simple, obvious calls-to-action; clear service breakdown. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["tyre-shops", "security-installers", "massage-therapists", "letting-agents", "carpet-cleaners"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "mot-centres",
    name: "MOT Centres",
    category: "Automotive",
    metaTitle: "MOT Centres Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for mot centres. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Get More Enquiries with a Stronger MOT Centres Website",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a mot centres business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in mot centres websites: fast mobile experience; clear service breakdown; simple, obvious calls-to-action; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["plumbers", "care-homes", "glaziers", "massage-therapists", "nail-salons"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "tyre-shops",
    name: "Tyre Shops",
    category: "Automotive",
    metaTitle: "Tyre Shops Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds tyre shops websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Tyre Shops Websites Built to Compete Locally",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a tyre shops business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in tyre shops websites: clear service breakdown; strong proof and trust signals; simple, obvious calls-to-action; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["car-dealers", "window-fitters", "estate-agents", "kitchen-fitters", "restaurants"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "car-dealers",
    name: "Car Dealers",
    category: "Automotive",
    metaTitle: "Car Dealers Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds car dealers websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Get More Enquiries with a Stronger Car Dealers Website",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a car dealers business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in car dealers websites: strong proof and trust signals; clear service breakdown; service-area clarity; simple, obvious calls-to-action. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["window-fitters", "boiler-engineers", "plumbers", "electricians", "locksmiths"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  // ─── Hospitality ────────────────────────────────────────────────────────
  {
    slug: "hotels",
    name: "Hotels",
    category: "Hospitality",
    metaTitle: "Hotels Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for hotels. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Hotels",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a hotels business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in hotels websites: simple, obvious calls-to-action; clear service breakdown; strong proof and trust signals; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["gyms", "letting-agents", "cafes", "solar-installers", "tree-surgeons"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "pubs",
    name: "Pubs",
    category: "Hospitality",
    metaTitle: "Pubs Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for pubs. Built for enquiries, trust and local visibility.",
    h1: "Pubs Websites Built to Compete Locally",
    intro: "Most customers decide who to contact in under a minute. If you’re a pubs business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in pubs websites: simple, obvious calls-to-action; fast mobile experience; service-area clarity; clear service breakdown. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["restaurants", "waste-removal", "driveway-companies", "barbers", "window-cleaners"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "takeaways",
    name: "Takeaways",
    category: "Hospitality",
    metaTitle: "Takeaways Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds takeaways websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Takeaways Websites Built to Compete Locally",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a takeaways business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in takeaways websites: fast mobile experience; simple, obvious calls-to-action; clear service breakdown; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["locksmiths", "barbers", "loft-conversions", "flooring-shops", "mot-centres"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  // ─── Health ────────────────────────────────────────────────────────
  {
    slug: "vets",
    name: "Vets",
    category: "Health",
    metaTitle: "Vets Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for vets. Built for enquiries, trust and local visibility.",
    h1: "Vets Websites Built to Compete Locally",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a vets business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in vets websites: clear service breakdown; service-area clarity; fast mobile experience; strong proof and trust signals. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["tree-surgeons", "cafes", "beauty-clinics", "waste-removal", "loft-conversions"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "chiropractors",
    name: "Chiropractors",
    category: "Health",
    metaTitle: "Chiropractors Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds chiropractors websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Get More Enquiries with a Stronger Chiropractors Website",
    intro: "Your website is often the first quote conversation you never get to attend. If you’re a chiropractors business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nResults depend on your market, competition and how consistently you follow up — but this setup gives you a serious competitive edge.",
    challenges: "What we see most often in chiropractors websites: service-area clarity; fast mobile experience; clear service breakdown; simple, obvious calls-to-action. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["carpet-cleaners", "locksmiths", "car-dealers", "dental-implants", "salons"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "opticians",
    name: "Opticians",
    category: "Health",
    metaTitle: "Opticians Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for opticians. Built for enquiries, trust and local visibility.",
    h1: "Get More Enquiries with a Stronger Opticians Website",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a opticians business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nYou get a fast website, an SEO foundation built for local search, and a review system that strengthens trust over time.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in opticians websites: clear service breakdown; simple, obvious calls-to-action; strong proof and trust signals; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["massage-therapists", "waste-removal", "pubs", "removal-companies", "painters-and-decorators"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "care-homes",
    name: "Care Homes",
    category: "Health",
    metaTitle: "Care Homes Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for care homes. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Care Homes Websites Built to Compete Locally",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a care homes business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in care homes websites: service-area clarity; fast mobile experience; clear service breakdown; simple, obvious calls-to-action. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["solar-installers", "dentists", "window-fitters", "opticians", "salons"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  // ─── Beauty ────────────────────────────────────────────────────────
  {
    slug: "beauty-clinics",
    name: "Beauty Clinics",
    category: "Beauty",
    metaTitle: "Beauty Clinics Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "GuardX builds beauty clinics websites that convert: fast pages, SEO foundations and a review system that strengthens credibility over time.",
    h1: "Get More Enquiries with a Stronger Beauty Clinics Website",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a beauty clinics business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nGuardX brings together conversion-focused design, SEO foundations, and automated review collection so your online presence works as a unit.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in beauty clinics websites: strong proof and trust signals; service-area clarity; simple, obvious calls-to-action; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["barbers", "construction-companies", "tree-surgeons", "massage-therapists", "plasterers"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "nail-salons",
    name: "Nail Salons",
    category: "Beauty",
    metaTitle: "Nail Salons Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Get a modern website, SEO-ready structure and review growth system for nail salons. Built for enquiries, trust and local visibility.",
    h1: "Web Design, SEO Foundation & Review Growth for Nail Salons",
    intro: "In local search, people compare options fast — and trust usually wins. If you’re a nail salons business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nWe can’t promise a specific ranking, but we can make sure your online presence is built to compete properly.",
    challenges: "What we see most often in nail salons websites: strong proof and trust signals; clear service breakdown; service-area clarity; fast mobile experience. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Want a quick scorecard for your current setup? We’ll tell you what to fix first.",
    relatedIndustries: ["flooring-shops", "letting-agents", "estate-agents", "barbers", "cctv-installers"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  {
    slug: "massage-therapists",
    name: "Massage Therapists",
    category: "Beauty",
    metaTitle: "Massage Therapists Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for massage therapists. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Get More Enquiries with a Stronger Massage Therapists Website",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a massage therapists business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in massage therapists websites: simple, obvious calls-to-action; clear service breakdown; strong proof and trust signals; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. Get a quick scorecard and see what’s holding enquiries back.",
    relatedIndustries: ["loft-conversions", "removal-companies", "glaziers", "scaffolders", "garages"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
  // ─── Health ────────────────────────────────────────────────────────
  {
    slug: "dental-implants",
    name: "Dental Implant Clinics",
    category: "Health",
    metaTitle: "Dental Implant Clinics Websites, SEO Foundation & Reviews | GuardX",
    metaDescription: "Web design, SEO foundations and review growth for dental implant clinics. Built to compete locally with a fast site, clear services and stronger trust signals.",
    h1: "Dental Implant Clinics Websites Built to Compete Locally",
    intro: "When someone needs help, they look you up, scan reviews, then decide. If you’re a dental implant clinics business, your site needs to do two jobs: build trust fast and make it easy to contact you.\n\nWe combine a modern, fast website, an SEO-ready structure, and a simple review-growth flow into one clear system.\n\nNo gimmicks — just the foundations that make it easier to win enquiries in competitive local markets.",
    challenges: "What we see most often in dental implant clinics websites: simple, obvious calls-to-action; strong proof and trust signals; fast mobile experience; service-area clarity. These gaps don’t just look messy — they reduce calls and quote requests.\n\nWe fix the fundamentals: clearer structure, stronger proof, and a review flow that keeps your reputation moving in the right direction. If you want, we can run a quick scorecard and show you the highest-impact improvements.",
    relatedIndustries: ["garages", "vets", "boiler-engineers", "mot-centres", "driveway-companies"],
    relatedLocations: ["sussex", "brighton", "london", "manchester", "birmingham"],
  },
]


export function getIndustryBySlug(slug: string): Industry | undefined {
  return industries.find((i) => i.slug === slug)
}

export function getIndustriesByCategory(category: Industry["category"]): Industry[] {
  return industries.filter((i) => i.category === category)
}

export const industryCategories: Industry["category"][] = [
  "Trades",
  "Home Services",
  "Property",
  "Automotive",
  "Health",
  "Beauty",
  "Hospitality",
]
